apiVersion: apps/v1
kind: Deployment
metadata:
  name: final
  labels:
    app: final
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: final
    spec:
      containers:
        - image: candesign/final
          imagePullPolicy: Always
          name: final
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: final
  labels:
    app: final
spec:
  type: LoadBalancer
  selector:
    app: final
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP